version: '2'
services:
  nginx:
    ports:
      - '8000:80'
    volumes:
      - ./src:/usr/share/nginx/html
    build:
      dockerfile: docker/nginx/Dockerfile.devel
      context: .

  node:
    ports:
      - '8001:3000'
    volumes:
      - ./src:/app
    command: tail -f /dev/null 
    build:
      dockerfile: docker/node/Dockerfile.devel
      context: .

